apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 664861096338.dkr.ecr.us-east-1.amazonaws.com/my-mysql:latest
    ports:
    - containerPort: 3306