# webapp-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: webapp-secret
  namespace: webapp-namespace
type: Opaque
data:
  app-secret-key: c2VjcmV0a2V5  # base64 encoded value for "secretkey"
